[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 1000
maxMessageSize = 1000
enableCORS = false

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
